import type { Command, Option } from 'commander';
import { COMMAND_REGISTRY, type CommandEntry, ROOT_SUMMARY } from '../commands/registry.js';

/**
 * docs/commands.md's generated region (ALI-951). `npm run docs:commands` writes it from the
 * registry and the Commander tree; commands-doc.test.ts fails when the committed region and
 * this renderer disagree. Prose outside the markers is hand-written and left alone.
 */
export const COMMANDS_DOC_START = '<!-- commands:start - generated by `npm run docs:commands`, do not edit by hand -->';
export const COMMANDS_DOC_END = '<!-- commands:end -->';

const TERM_WIDTH = 30;

function flagsOf(cmd: Command): string {
  const flags = (cmd.options as Option[]).map((o) => o.long ?? o.short ?? o.flags).filter(Boolean);
  return flags.length ? `flags: ${flags.join(' ')}` : '';
}

function usageOf(cmd: Command, path: string[]): string {
  const args = cmd.registeredArguments.map((a) => (a.required ? `<${a.name()}>` : `[${a.name()}]`));
  return ['align', ...path, cmd.name(), ...args].join(' ');
}

function row(term: string, description: string): string {
  return term.length >= TERM_WIDTH
    ? `${term}\n${' '.repeat(TERM_WIDTH)}${description}`
    : `${term.padEnd(TERM_WIDTH)}${description}`;
}

function renderCommand(cmd: Command, path: string[], lines: string[]): void {
  lines.push(row(usageOf(cmd, path), cmd.description()));
  const flags = flagsOf(cmd);
  if (flags) lines.push(`${' '.repeat(TERM_WIDTH)}${flags}`);
  for (const sub of cmd.commands) {
    if (sub.name() === 'help') continue;
    renderCommand(sub, [...path, cmd.name()], lines);
  }
}

function renderEntry(entry: CommandEntry, program: Command, lines: string[]): void {
  for (const name of entry.names) {
    const cmd = program.commands.find((c) => c.name() === name);
    if (!cmd) throw new Error(`registry names \`${name}\` but the program did not register it`);
    lines.push('');
    renderCommand(cmd, [], lines);
    const alias = cmd.alias();
    if (alias) lines.push(row(`align ${alias}`, `alias of align ${name}, deprecated - prints one line on stderr per run`));
  }
}

/** The whole region between the markers, markers excluded. */
export function renderCommandsReference(program: Command): string {
  const lines: string[] = [];
  const entries = COMMAND_REGISTRY.filter((e) => !e.internal);
  if (entries.length === 0) throw new Error('COMMAND_REGISTRY is empty');

  lines.push('## Everyday', '', 'What `align --help` shows.', '', '```');
  lines.push(row('align', ROOT_SUMMARY));
  for (const entry of entries.filter((e) => e.visible)) renderEntry(entry, program, lines);
  lines.push('```', '');

  lines.push('## Everything else', '', 'Hidden from `align --help`; every one still runs.', '', '```');
  let first = true;
  for (const entry of entries.filter((e) => !e.visible)) {
    if (!first) lines.push('');
    first = false;
    lines.push(`# ${entry.summary}`);
    renderEntry(entry, program, lines);
  }
  lines.push('```');
  return lines.join('\n');
}

/** The text between the markers in a doc, or null when the markers are missing. */
export function generatedRegion(doc: string): string | null {
  const start = doc.indexOf(COMMANDS_DOC_START);
  const end = doc.indexOf(COMMANDS_DOC_END);
  if (start < 0 || end < 0 || end < start) return null;
  return doc.slice(start + COMMANDS_DOC_START.length, end).replace(/^\n/, '').replace(/\n$/, '');
}

/** The doc with its generated region replaced; throws rather than appending when the markers are missing. */
export function withGeneratedRegion(doc: string, region: string): string {
  const start = doc.indexOf(COMMANDS_DOC_START);
  const end = doc.indexOf(COMMANDS_DOC_END);
  if (start < 0 || end < 0 || end < start) throw new Error(`docs/commands.md is missing the ${COMMANDS_DOC_START} .. ${COMMANDS_DOC_END} markers`);
  return `${doc.slice(0, start + COMMANDS_DOC_START.length)}\n${region}\n${doc.slice(end)}`;
}
