/**
 * ALI-196 spike: render the decisions file Align owns, and the one line that imports it.
 *
 * MECHANISM. Align owns `.align/decisions.md` outright and the user's CLAUDE.md gains a single
 * import line. That satisfies Tom's augment-never-overwrite constraint STRUCTURALLY rather than
 * carefully: nothing here parses a document containing content we did not write, so the worst
 * bug available is a wrong file that holds nothing of theirs.
 *
 * The alternative, splicing a managed block inside CLAUDE.md, needs a marker parser.
 * `fillGeneratedRegions` in align-stack is the one that already has the four guards for that
 * job, and `@align/docs-pipeline` is `private: true` in a different repo, so align-cli cannot
 * import it. A reimplementation would be a second lenient-matcher/strict-builder in the world -
 * the exact bug class those guards close (code-style.md).
 *
 * OPEN CORE. Nothing here selects or ranks anything. Which decisions are current, relevant and
 * unsuperseded is a gateway query; this module formats a list and writes a file, which is
 * plumbing.
 */

export interface ContextDecision {
  title: string;
  /** e.g. `align-stack#1441`. Stable, human-quotable, and the deterministic sort key. */
  cite?: string;
  /** Where it was DECIDED. Never interchangeable with a decision_url into the Align app. */
  sourceUrl?: string;
}

export const ALIGN_CONTEXT_PATH = '.align/decisions.md';
export const ALIGN_IMPORT_LINE = `@${ALIGN_CONTEXT_PATH}`;

/**
 * Deterministic order, independent of what the graph happened to return.
 *
 * Without this, a LIMIT with no ORDER BY upstream reorders the block between runs and defeats
 * idempotence without a single decision having changed (tdd.md's fourth shape).
 */
function ordered(decisions: ContextDecision[]): ContextDecision[] {
  return [...decisions].sort((a, b) =>
    (a.cite ?? '').localeCompare(b.cite ?? '') || a.title.localeCompare(b.title),
  );
}

/**
 * Render the file. Byte-identical for identical input, which is the acceptance test for the
 * whole feature: a file that differs between runs turns every regeneration into a git diff.
 *
 * NOTE THE ABSENCE OF A TIMESTAMP, which is deliberate and load-bearing. "Generated on <date>"
 * is the obvious header to write and it breaks idempotence a day later. It also passes a naive
 * idempotence test, because two calls inside one test produce the same date - so the no-date
 * assertion is a separate test rather than an implied one.
 */
export function renderDecisionsFile(decisions: ContextDecision[]): string {
  const header = [
    '# Decisions (generated by Align)',
    '',
    'Generated from your decision graph. Edits here are overwritten; this file is owned by',
    '`align`. Re-run the generator to bring it up to date.',
    '',
  ];

  if (decisions.length === 0) {
    // "Nothing found" and "the fetch failed" must not look alike, so say which this is.
    // An empty section reads as a claim that no decisions exist (ALI-414, new surface).
    return `${[...header, 'No decisions have been captured for this repository yet.'].join('\n')}\n`;
  }

  const body = ordered(decisions).map((d) => {
    const cite = d.cite ? ` (${d.cite})` : '';
    const link = d.sourceUrl ? ` - ${d.sourceUrl}` : '';
    return `- ${d.title}${cite}${link}`;
  });

  return `${[...header, ...body].join('\n')}\n`;
}

/** Does this file already import the generated context? */
export function hasImportLine(claudeMd: string): boolean {
  return claudeMd.includes(ALIGN_IMPORT_LINE);
}

/**
 * Append the import line, once.
 *
 * The only write to a file the user owns, and deliberately the dumbest possible one: an append
 * cannot reorder or delete what is already there. It does not parse, so a file that merely
 * mentions align is not mistaken for one that imports it.
 */
export function appendImportLine(claudeMd: string): string {
  if (hasImportLine(claudeMd)) return claudeMd;
  const separator = claudeMd.endsWith('\n') ? '' : '\n';
  return `${claudeMd}${separator}\n${ALIGN_IMPORT_LINE}\n`;
}
