/**
 * ALI-933: `align context inject` - the read-path counterpart to `align check --advisory`.
 *
 * The write path (agent-rules.ts's Pre/PostToolUse hooks) reaches the model on every edit.
 * Nothing reached the model on SESSION START before this - the graph's content only landed
 * if the model chose to open .align/decisions.md or call an MCP tool. This command is what a
 * SessionStart hook shells out to: it prints the already-synced decisions file wrapped in the
 * JSON shape a host's hook reads back, so the content lands whether or not the model asked.
 *
 * Deliberately reads .align/decisions.md rather than fetching the graph itself: `align context
 * sync` already owns that fetch (network, auth, a spinner, a non-zero exit on failure - none of
 * which belong inside a hook that must stay fast and offline-safe). Reusing the file `sync`
 * already writes is "do not reinvent the rendering" taken literally: no rendering logic lives
 * in this file at all.
 *
 * Test List:
 * 1. no .align/decisions.md - prints nothing, exits 0 (fail open: nothing synced yet)
 * 2. .align/decisions.md present - prints the SessionStart hookSpecificOutput JSON, one line
 * 3. the injected content is the file's content, not a rendering of it (parse the JSON back)
 * 4. whitespace-only file - prints nothing (an empty additionalContext is not worth a line)
 * 5. never throws on an unreadable file - fails open like every other host shim in this repo
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { Command } from 'commander';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { registerContextCommand } from '../commands/context.js';

let repo: string;
let prevCwd: string;

beforeEach(() => {
  repo = fs.mkdtempSync(path.join(os.tmpdir(), 'ali933-inject-'));
  prevCwd = process.cwd();
  process.chdir(repo);
});

afterEach(() => {
  process.chdir(prevCwd);
  fs.rmSync(repo, { recursive: true, force: true });
  vi.restoreAllMocks();
});

async function runInject(): Promise<{ stdout: string }> {
  const program = new Command();
  program.exitOverride();
  registerContextCommand(program);
  let stdout = '';
  const writeSpy = vi.spyOn(process.stdout, 'write').mockImplementation((chunk: unknown) => {
    stdout += String(chunk);
    return true;
  });
  try {
    await program.parseAsync(['node', 'align', 'context', 'inject']);
  } finally {
    writeSpy.mockRestore();
  }
  return { stdout };
}

describe('align context inject', () => {
  it('prints nothing when .align/decisions.md has never been synced', async () => {
    const { stdout } = await runInject();
    expect(stdout).toBe('');
  });

  it('prints the SessionStart hookSpecificOutput JSON when the file exists', async () => {
    fs.mkdirSync(path.join(repo, '.align'), { recursive: true });
    fs.writeFileSync(path.join(repo, '.align', 'decisions.md'), '# Decisions\n\n- Use Postgres 16\n');
    const { stdout } = await runInject();
    const lines = stdout.trim().split('\n');
    expect(lines).toHaveLength(1);
    const parsed = JSON.parse(lines[0]);
    expect(parsed).toHaveProperty('hookSpecificOutput.hookEventName', 'SessionStart');
    expect(typeof parsed.hookSpecificOutput.additionalContext).toBe('string');
  });

  it('injects the raw file content, not a re-rendering of it', async () => {
    const content = '# Decisions (generated by Align)\n\n- Use Postgres 16 (api#1441) - https://github.com/x\n';
    fs.mkdirSync(path.join(repo, '.align'), { recursive: true });
    fs.writeFileSync(path.join(repo, '.align', 'decisions.md'), content);
    const { stdout } = await runInject();
    const parsed = JSON.parse(stdout.trim());
    expect(parsed.hookSpecificOutput.additionalContext).toBe(content.trim());
  });

  it('prints nothing for a whitespace-only decisions file', async () => {
    fs.mkdirSync(path.join(repo, '.align'), { recursive: true });
    fs.writeFileSync(path.join(repo, '.align', 'decisions.md'), '   \n\n\t\n');
    const { stdout } = await runInject();
    expect(stdout).toBe('');
  });

  it('fails open (no throw, no output) when the file cannot be read as UTF-8 text', async () => {
    // A directory named decisions.md is unreadable as text - stands in for any read error
    // that isn't ENOENT, without needing to fake filesystem permissions cross-platform.
    fs.mkdirSync(path.join(repo, '.align', 'decisions.md'), { recursive: true });
    await expect(runInject()).resolves.toEqual({ stdout: '' });
  });
});
